### ISSUE TITLE
Implement "lock" functions in engage.py

### ISSUE THREAD

**Issue by radka-j** [alan-turing-institute/repro-catalogue#10]
Subtask of #6

The [engage.py](https://github.com/alan-turing-institute/repro-catalogue/blob/2745de147f5cb0ba5c8e045e03c868dcbe3d1682/catalogue/engage.py) file calls functions not yet implemented anywhere. These are:
- [x] `lock`
- [x] `unlock`
- [x] `check_against_lock`

From the README: 
- `lock()` should create a `.loc` file after `catalogue engage` is called
- `unlock()` reads and deletes the `.loc` file after `catalogue disengage` is called
- `check_againats_lock()` checks the created hashes after analysis against hashes in the `.loc` file (before analysis)

**Comment by Islast** [comment]
Hey! A lot of the code is described, but not yet implemented- this is one such example. In general where there are gaps in the code these are places where I knew what I would want the code to *do* so I gave the function a relevant name and deferred implementing it until later

**Comment by radka-j** [comment]
The `lock()` function creates a file (currently `<TIMESTAMP>.json` saved in the WD) when `catalogue engage` is called. 

The `unlock()` function is meant to read and delete this file when `catalogue disengage` is called. For this it needs to keep track of the timestamp under which it was originally created.

I am not sure what is best practice for doing this. @edaub  - any ideas?

One option is to simply look for the last (only?) created `json` file in some temporary directory for these temporary files and read that.  Another option might be to save the TIMESTAMP as an environment variable (or something like that) when the file is created.

**Comment by Islast** [comment]
My plan was to have `lock()` create a consistently named file, say `.lock` in a specific directory, and to have `unlock()` read and delete `.lock()`  and create the `<TIMESTAMP>.json` file.
Thus `unlock` always knows it is looking for `directory for catalogue files/.lock` and does not have to worry about timestamps

**Comment by radka-j** [comment]
Ok that is more straightforward than what I was thinking. That sounds good. Thanks! :)
