### ISSUE TITLE
Documentation icons not displayed in readthedocs

### ISSUE THREAD

**Issue by edaub** [alan-turing-institute/repro-catalogue#102]
The nice icons we have in the readme don't show up on the readthedocs page. Investigate how to make these show up.

**Comment by kevinxufs** [comment]
It seems like this package should in theory enable our mark down emojis:

https://github.com/sphinx-contrib/emojicodes

I modified my conf.py file (and committed it to my branch) to see if this would make it work but I'm not sure if my readthedocs file is reacting to the change, or if there's anything I need to do to rebuild it.
