### ISSUE TITLE
Fix engage test

### ISSUE THREAD

**Issue by kevinxufs** [alan-turing-institute/repro-catalogue#116]
On the config branch we keep experiencing a problem with the directories. It makes one of the engage tests fail.

Eric has identified that it is a problem with the root directories. In master, the root directory is the repository folder, whilst in the config branch the root directory is root `/`.  Essentially, the test seems to set the root directory as `/` which leads to a permission error when trying to create a sub directory.

I'm going to document some observations here.

According to the pytest documentation: https://docs.pytest.org/en/stable/customize.html
It seems that pytest has a specific way of determining the root directory each time that are based around the arguments of the test. The engage test that has problems uses the following arguments:

`git_repo`
`test_args`
`capsys`

In the config branch we have modified `git_repo` to add additional fixtures, but I'm not sure why this would lead to a problem.

I tried the following command:

`pytest --rootdir=<expected root>`
Where the `<expected root>` is something like `/home/kevinxu/repro-catalogue`, i.e. the sort of root that master uses.

Thid does not cause the test to work.

What does seem to make the test work is to add a line like `os.chdir(<expected root>)` (within the test) alongside `pytest --rootdir=<expected root>` (run in terminal)

This is of course not a solution as it requires hardcoding the `os.chdir` line. The reason I suspect it works is because  `pytest --rootdir=<expected root>` presumably tells us to go back to the specified root directory whenever needed. The altnernative is to constantly specify movement between the `<expected_root>` and `git_repo`.

**Comment by kevinxufs** [comment]
Would you have any idea what might be happening here @radka-j ? Thanks!

**Comment by kevinxufs** [comment]
It's not an explanation or an adequate full solution, but the following also works @edaub :

1) Outside of any of the tests:
`cwd = os.getcwd()`

2) In the engage test
`os.chdir(cwd)`

It should be unsurprising that this works, as this simply gets us back to the master version. We just have to move to the correct root directory instead of being there for free

The problem remains in determining why in this branch the root directory gets set differently. See the rootdir algorithm according to the documentation:

```
Here is the algorithm which finds the rootdir from args:

    Determine the common ancestor directory for the specified args that are recognised as paths that exist in the file system. If no such paths are found, the common ancestor directory is set to the current working directory.

    Look for pytest.ini, pyproject.toml, tox.ini, and setup.cfg files in the ancestor directory and upwards. If one is matched, it becomes the configfile and its directory becomes the rootdir.

    If no configuration file was found, look for setup.py upwards from the common ancestor directory to determine the rootdir.

    If no setup.py was found, look for pytest.ini, pyproject.toml, tox.ini, and setup.cfg in each of the specified args and upwards. If one is matched, it becomes the configfile and its directory becomes the rootdir.

    If no configfile was found, use the already determined common ancestor as root directory. This allows the use of pytest in structures that are not part of a package and don’t have any particular configuration file.
```

**What is confusing to me is that in master, the directories for `test_args` and `git_repo` are both along the lines of `/tmp/..` which means their ancestor should in theory (following by the first rule) be root `/`.** 

That would make sense to be me, but it would also mean that master should not work?

**Comment by kevinxufs** [comment]
When running `pytest` it also shows the overall root_dir being used, which is indeed `<expected root>`.

 Therefore the problem seems specific to this engage test. Elsewhere, it seems to be setting the correct root.

**Comment by kevinxufs** [comment]
I ran the following test by creating three fixtures:

a = `/hi/...`
b = `/hi/...`
c = `/hi/...`

I then ran a test using these three fixtures. 
My expectation is that I would end up with a root directory of `/hi` but for some reason I still got a root directory of `/`

I then ran the same on master and I got root directory `<expected root>`. 

I may be on the wrong track and the rootdir is not being calculated based on the arguments.

**Comment by kevinxufs** [comment]
So some more testing led to the conclusion that this problem seems rather specific to `test_engage.py`.

So I created the following test:

```
def test_root(git_repo, test_args, capsys):
    print(os.getcwd())
    assert False
```

I then added this to two different test files (`test_catalogue.py` and `test_engage.py`) and they give different outputs.

`test_catalogue.py` gives me `<expected root>` whilst `test_engage.py` gives me `/`

(Both done in config branch)

**Comment by kevinxufs** [comment]
So what seems to be an issue is that with literally every other test file, they have the correct root_dir.

Furthermore, I can create an entirely new test file with the exact same content of test_engage, and I get the correct root directory.

However, the moment I change this new test file's name to `test_engage` it all falls apart and the root directory becomes incorrect.

![image](https://user-images.githubusercontent.com/48526846/90418199-b9894800-e0ac-11ea-9934-bc255a173d53.png)

I don't understand why this is happening. I assume there must be some kind of script that explicitly refers to `test_engage.py` that is causing this. Otherwise I could just rename `test_engage.py` and things would be fine.

I've noted that `test_engage` uses the full path whilst `test_config` uses the relative.

**Comment by radka-j** [comment]
@kevinxufs I don't have any immediate thoughts on this but I will try to look at this some more!

Quick question (just trying to make sure I understand your previous comments): what do you mean that it is an issue specific to `engage`? It seems that in the config tests you also had to include `os.chdir(get_repo)` to avoid getting errors - is that correct? Are there some particular issues in the `engage` tests that the `config` tests  don't have?

**Comment by kevinxufs** [comment]
@radka-j 
Thanks so much for taking a look

I find it a bit confusing to explain but if you look at the screen shot you can see that I have repeated this `test_root` twice. Once in `test_config` and once in `test_engage`. Both of these tests were added as the first test for each file.

For some reason, in `test_config` we are getting the correct root directory (or rather, the _expected_ root directory) whilst in `test_engage` we are simply getting `/`. This is surprising because both tests use the same arguments and are in the same sort of location so I'm confused why the root directories would be different (see documentation above on how the root is determined).

In fact, I tried removing all of the engage tests apart from `test_root` and I get the same sort of issue with the `/` root directory.
Similarly, I can remove all the config tests (including those where I use `chdir`) and I get back this expected root directory.

The incorrect root directory ends up leading to an issue when running engage because we cannot create new directories from `/`.

I hope that clarifies something!

**Comment by kevinxufs** [comment]
@edaub looks like the plot thickens and this is related to the `chdir` that @radka-j mentioned.

With some more messing around with the directory, I've found the problem. Or at least, I understand a bit more.

The issue is with `test_config.py` which kind of makes sense.

Essentially what is happening is that `test_engage.py` is runs directly after `test_config.py` due to its alphabetical ordering!!

At some point in `test_config.py` I change directory to `git_repo`. This path looks like `/tmp/..`. For whatever reason, after the test runs, it presumably deletes the `tmp` but keeps me in the same ancestor directory, i.e. `/` directory.

This then transfers to `test_engage.py`, meaning it starts running in the `/` root directory, which is what leads to these problems.

Here's further evidence: if we run `pytest test/test_engage.py` everything magically works. This is because it never got redirected to the `/` root directory by `test_config.py`!

How do we solve this?

There's the lazy way and what is probably the legitimate way.

The simple way basically just tells us to move back to the correct expected directory at the end of `test_config.py`.

The legitimate way would be to figure what is happening with the directories in `test_config.py` so we never have to switch directories.

**Comment by edaub** [comment]
Yes, I was simultaneously coming to the same conclusion based on systematically adding in one test at a time from your branch.

Having looked more closely at what you are doing, do you really need to be in the git repo to do these config tests? The check that you are in a git repo only matters when you run engage/disengage, so running config shouldn't need to do any git checks, correct? I think you should be able to do these same tests without ever changing directories in the first place.

**Comment by kevinxufs** [comment]
Hi Eric,

So the reason we move to git repo is just to have an empty directory that we can manipulate. This is because a lot of the config tests depend on there being (or not being) some kind of config file in the directory. This was to avoid creating / deleting config files within the repro-catalogue directory.

**Comment by edaub** [comment]
Ah, so then you should do this in a temporary directory instead. That would be the correct way to do these checks.

**Comment by kevinxufs** [comment]
Is it related to this: https://docs.pytest.org/en/stable/tmpdir.html

Should I be creating a tmpdirectory fixture, distinct from the git repo fixture?

Thanks

**Comment by kevinxufs** [comment]
Thanks @edaub 

I've added the tmpdir fixture to all the tests and they seem to work fine (the engage issue is gone)

I still run something like `os.chdir(tmpdir)` (without ever switching back) - I just wanted to check that this is fine before I push the code.

**Comment by radka-j** [comment]
@kevinxufs well done!

There is also a fixture in conftest that creates a directory in a temporary workspace (it copies the fixtures directory) and returns the path. It sounds like you got it all working but I am also happy to have a chat about this implementation if that was useful. Let me know :)

**Comment by kevinxufs** [comment]
Thanks a lot @radka-j 

Was this with the `copy_fixtures_dir` fixture? I tried using this but I seem to end up with a similar error to earlier - is suspect that `copy_fixtures_dir` also uses a `/` ancestor?

Would be great to chat some time more generally about your test implementation :)

**Comment by radka-j** [comment]
@kevinxufs you're right, you'd still need to do what you are doing now (e.g., `os.chdir(copy_fixtures_directory)`) for it to work. So that doesn't address the problem you were solving! I was just thinking of other temp directories we have around. 

I looked through the tests now - everything works for me and they look good!  :)
