### ISSUE TITLE
Write engage csv test

### ISSUE THREAD

**Issue by kevinxufs** [alan-turing-institute/repro-catalogue#118]
I'm making a few modifications to how the engage function checks csv file extensions. 

I've noticed that we don't seem to have a test that explicitly checks that csv files are created.

The functionality seems to work when manually testing, but I think we should have a unit test for this as well.

I've started writing this but I get the following kind of error:

`KeyError: 'disengage' (line 326)`

It seems to be something wrong with the process of writing the csv file?

**Comment by kevinxufs** [comment]
Seems like a problem so far with my `hash_dict` - it doesn't seem to have a `disengage` key.

**Comment by kevinxufs** [comment]
I found a fix, I'm not quite sure why.

I did

`setattr(test_args, 'command', 'disengage')` 
This seems to force the contrust_dict function to work correctly for the test.

I'm adding two tests here and will commit shortly.

@radka-j could you check that this makes any kind of sense!

**Comment by radka-j** [comment]
@kevinxufs what branch can I view this on?

**Comment by kevinxufs** [comment]
Thanks Radka, I was more just checking whether the idea made sense.

I'm just finishing off writing the test, will push it in about 10 minutes sorry!

**Comment by radka-j** [comment]
No worries! It's hard to comment without seeing what the test is trying to do.

But it sounds like you are checking for the existence of a csv file and this happens after calling the `disengage` command. I am guessing somewhere in the code there is a check that catalogue is in `disengage` mode? Does that sound right?

The line that you have included (`setattr(test_args, 'command', 'disengage')`) will set the `command` argument in `test_args` to be `disengage` (i.e., pretend someone has called `catalogue disengage`) so at a quick glance that seems to make sense :)

**Comment by kevinxufs** [comment]
@radka-j 

I've now pushed it onto branch `feature/config`.

The main change is that I now want to create a csv file only if the user provides a file that has a `.csv` extension. In every other case, we will default to a json file. (I wonder whether we should have an error message if they give an input for `csv` but it is not a csv file.

I've written some tests to show this.

**Comment by radka-j** [comment]
@kevinxufs I had a quick look at the `KeyError: disengage` you were getting earlier and your fix. It makes perfect sense. 

The `test_args` are a stand-in for the `args` that the `engage` and `disengage` functions take as input parameters. The `hash_dict` that gets created in `disengage` includes a key based on the value of `args.command` (see the `construct_dict` function).  The `test_args.command` value is set to `engage` by default. The `save_csv` function was looking for `disengage` to be in the `hash_dict` keys but it did not exist. You changed `test_args.command` to `disengage` which means `hash_dict` will now have a `disengage` key and that makes the test work. Well done :)

**Comment by kevinxufs** [comment]
Thanks @radka-j for taking a look at this. Your explanation makes a lot of sense - the only thing I was wondering is why the directly previous test doesn't need to do this? It seems that they are also looking to generate a results file (although for them it is json only).

**Comment by radka-j** [comment]
@kevinxufs the `save_csv` function goes through the `hash_dict` and formats it before it can be saved to csv in the process of which it checks the keys (it has to do this). The `store_hash` function which creates the json files just saves the `hash_dict` to file without having to do anything with the content. Additionally, we use `store_hash` to store the file when calling `engage` and `disengage` so either key is acceptable.

I don't feel that adding checks for this are necessary but if we were to add it, it would go in the `disengage` command. It already includes some checks of the keys in `compare_`, so we could add a check for the `disengage` key in `hash_dict` there as well.

**Comment by kevinxufs** [comment]
Thanks @radka-j that makes a lot more sense to me :)

**Comment by kevinxufs** [comment]
Closed as #113 was merged.
