### ISSUE TITLE
Record parameters used in analysis

### ISSUE THREAD

**Issue by edaub** [alan-turing-institute/repro-catalogue#14]
If analysis scripts take command line parameters as inputs, we need a way to record those if we want to be able to reproduce the analysis. Maybe this could be done by accessing bash history and tracing back to the previous engage? Particularly important if the model depends on setting some random number seed.

**Comment by Islast** [comment]
This is a very interesting idea- I hadn't thought this far. 
Perhaps `catalogue engage` could launch a process to log standard input. Would it be easy to find and kill this process when we run `catalogue disengage`? If not perhaps could do away with disengage and just have `catalogue engage` open a shell and have the `disengage` functionality occur when the shell is closed.

**Comment by martintoreilly** [comment]
One [suggested method for doing this on Linux](https://confluence.atlassian.com/confkb/how-to-enable-command-line-audit-logging-in-linux-956166545.html). @jemrobinson Has also been looking at linux logging more generally.

>1. Login to the linux box and assume root 
>
> `sudo su -` 
>
>2. Edit /etc/profile and add the following lines to the bottom of the file: 
>```
># command line audit logging
>function log2syslog
>{
>   declare COMMAND
>   COMMAND=$(fc -ln -0)
>   logger -p local1.notice -t bash -i -- "${USER}:${COMMAND}"
>}
>trap log2syslog DEBUG
>```
>3. Save and exit /etc/profile
>4. Edit /etc/rsyslog.conf and add the following lines to the bottom of the file: 
>```
># command line audit logging
>local1.* -/var/log/cmdline
>```
>5. Save and exit /etc/rsyslog.conf 
>6. Either restart the rsyslog service, or restart the whole machine to release all user sessions - forcing a reload of the bash profile and enacting the changes 
>`/etc/init.d/rsyslog restart`
>7. The audit logging will be visible under /var/log/syslog and /var/log/cmdline and will look like this: 

[**Edit 1:** Doesn't lend itself to being turned of and off with `engage` and `disengage`, though those could set the time period of interest to extract commands from the log. Also is probably a no-no unless we can ensure that user A won't see user B's commands (from a user isolation security perspective - filtering by user would be sufficient to get only the current user's command history).]

[**Edit 2:** Could potentially have the `/etc/profile` script log to a file in each user's home directory?]

**Comment by jemrobinson** [comment]
Logging every command that every user enters feels over-intrusive. There's also the risk that this will leak credentials if anyone enters them on the command line.

**Comment by KirstieJane** [comment]
I have a pretty strong opinion here that we should just write the command with the arguments into a script! I’d say anything that isn’t in the version controlled code archive isn’t reproducible. No need to adapt this tool to capture the equivalent of using a gui at the command line.

**Comment by edaub** [comment]
Totally reasonable -- as long as the information on how to run the analysis is captured somewhere I think this is fine (and probably easier in the short term for the analysts to just version control a shell script to run everything in a deterministic way). We won't worry about this then (I will close the issue, and re-open if we decide we need this at a later date).
