### ISSUE TITLE
What hash algorithm?

### ISSUE THREAD

**Issue by edaub** [alan-turing-institute/repro-catalogue#15]
Is SHA-1 sufficient to prevent collisions (40 hex character message digest), or do we need one of the longer ones? Also there was discussion about ensuring character encodings didn't lead to different hash digests for the input data and anything else that might violate platform dependence.

**Comment by Islast** [comment]
Good question. I've been using sha512 out of a general sense that it was stronger (i think from something I read on Wikipedia) but I really don't have expertise on this matter

**Comment by radka-j** [comment]
Do we know someone who might be able to advise on this?

**Comment by edaub** [comment]
I think that since we haven't really had a good reason to use anything else, we should stick with sha512. The only strong argument for a shorter one is readibility, but since the user is never really meant to interact with the hash values directly this isn't really an issue.
