### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by edaub** [alan-turing-institute/repro-catalogue#17]
Implement semantic versioning to give every commit to master a unique release number. I usually like to have this maintained in `setup.py` (numpy is a good example). Any commits on a development branch have additional versioning information.

**Comment by edaub** [comment]
@radka-j has submitted a PR to start versioning. Depending on preferences, there are a few ways we might set up a branching/workflow model around this for future updates.

Currently, we have a single master branch, with work done on feature branches that are merged directly into master. If we think a single branch model is appropriate for this project, one model is to keep this workflow and update the `x.y.z` version number on every merge into master. A variant would be to update the prerelease version on every merge into master, but only officially "release" certain ones by updating the `x.y.z` version and tagging those. In both cases, we always branch off of master and merges into master change the version number.

Alternatively, we could adopt a long-running development branch model which formalizes a combination of the two models above. New feature work branches off of the development branch, and every commit onto the development branch increments the prerelease version. Periodically, the master branch is updated from the development branch, which increments the `x.y.z` version number. It's a bit more complicated than the single branch model, and the complexity of the project may not warrant keeping two branches active in this way.

Thoughts on this question are welcome, particularly from @radka-j and @LouiseABowler as they are doing most of the work!

**Comment by radka-j** [comment]
I like both workflows! But I agree that given the size of the project, the first more lightweight approach might work better here. I am flexible on this though :)

**Comment by radka-j** [comment]
Related question to this: tomorrow I plan to work on issue #44. Would this be considered a minor or a micro update? Or can it still be considered part of `1.0.0`
