### ISSUE TITLE
Fix hash_input and hash_output function

### ISSUE THREAD

**Issue by radka-j** [alan-turing-institute/repro-catalogue#41]
At the moment, `catalogue` assumes that `input_data` is a directory. This impacts how the input is processed and hashed.

However, it is conceivable that someone would give a path to a specific data file. In that case, the file is not read when creating the hash under the current implementation.

The `hash_input` function should check whether the given path is a file or a directory and call the appropriate hash function (`hash_dir_full` or `hash_file`). Or it should fail if someone provides a file path.

**Comment by radka-j** [comment]
This is also true for the ~`hash_code` and~ `hash_output` functions.

**Comment by edaub** [comment]
My current checkout of master works fine if files are passed for the code and input data, but does not work correctly for the output. Were you having problems with those?

**Comment by radka-j** [comment]
Sorry I should have been clearer. You get a hash back but it's not a hash of the file. The returned hash is what you would get if there was no input provided.

**Comment by edaub** [comment]
Ah, I see. I think code still works, though, right? The `check_parent_directories` flag should handle that case.

**Comment by radka-j** [comment]
Ah yes code works because that is just the git hash.
