### ISSUE TITLE
Resolve circular dependency in output directory

### ISSUE THREAD

**Issue by edaub** [alan-turing-institute/repro-catalogue#52]
The `CATALOGUE_DIR` global variable resides in the `engage` module, which depends on the `compare` module to check that the engage/disengage hashes match. However, if we want to be able to look for CSV files in the output directory in `compare` mode, then we have to import `engage` which introduces a circular dependency. The tool runs from the command line, but if you try to import things it doesn't work.

There are a few ways I can see to resolve this:

1. Move global output directory definition to `utils`, which does not rely on any other module, and import where needed
2. Move output directory to the parser file and incorporate into `args`, which can then be passed as a function argument and removes global variable
3. Make the output directory an command line argument and incorporate into `args`, then handle as previous case
4. Remove it altogether and require users to specify path for output, and then keep `.lock` file in the current working directory

I moved it to utils for the sake of making the tests run for the moment, but I probably have a slight preference for a combination of 2 and 3 by making it a command line option but providing a sensible default. Thoughts?

**Comment by radka-j** [comment]
I agree, same as with the other dir/file paths it should be a configurable `arg` with a default.
