### ISSUE TITLE
Add git section to README

### ISSUE THREAD

**Issue by radka-j** [alan-turing-institute/repro-catalogue#65]
A pre-requisite for using the tool is that the code is in a git repository. This is mentioned in a sentence in the README but should be made clearer. Include a section (probably after introduction) in the README that:
- explains this pre-requisite
- gives guidelines on not including data and results
- includes a `.gitignore` template

**Comment by LouiseABowler** [comment]
I can take this one, I've already got an open PR with edits to the README going on 🙂
