### ISSUE TITLE
Set up all-contributors bot

### ISSUE THREAD

**Issue by LouiseABowler** [alan-turing-institute/repro-catalogue#66]
One for when we've streamlined the README a bit as we have plenty of people to acknowledge already! 🚀 

A guide to setting up the bot is [here](https://allcontributors.org/docs/en/bot/overview); see also the [GitHub repo](https://github.com/all-contributors/all-contributors-bot) for the bot itself 🤖

**Comment by radka-j** [comment]
I think I've set it up, now we just need to try using it.

**Comment by radka-j** [comment]
@all-contributors add @LouiseABowler

**Comment by radka-j** [comment]
@all-contributors add @LouiseABowler for doc ideas review projectManagement

**Comment by radka-j** [comment]
it works!

**Comment by LouiseABowler** [comment]
That's great! One thing we found when using the bot for the Turing Way is that the PRs don't always neatly merge if you have several open at the same time - so it's best to add contributor, merge, add next contributor, merge... rather than opening all the PRs and then trying to merge them all at once.

**Comment by radka-j** [comment]
@LouiseABowler good to know! Are you happy with the contribution names I added for you? Is it possible to add to that list by just referencing you again with another type of contribution?

**Comment by LouiseABowler** [comment]
Yep, they look good so far - and hopefully we can add some more (is there one for packaging?) tomorrow 😄 

You should be able to add more to my list with further PRs; I think the same point I mentioned in the earlier comment might still apply though (so best to merge one PR before adding further contributions for one person).

**Comment by radka-j** [comment]
@all-contributors add @LouiseABowler for design maintenance

**Comment by radka-j** [comment]
@all-contributors add @Islast for design ideas code doc

**Comment by radka-j** [comment]
@all-contributors add @KirstieJane for design ideas infra

**Comment by radka-j** [comment]
@all-contributors add @sgibson91 for code review

**Comment by radka-j** [comment]
@all-contributors add @kevinxufs for review userTesting

**Comment by radka-j** [comment]
@all-contributors add @edaub for design ideas code doc review maintenance projectManagement

**Comment by radka-j** [comment]
@all-contributors add @radka-j for design ideas code review doc maintenance projectManagement infra

**Comment by radka-j** [comment]
I think I got everyone now (that was fun! haha). Please add any contributors/contributions if I missed anyone or anything!
