### ISSUE TITLE
Some comments on the README

### ISSUE THREAD

**Issue by kevinxufs** [alan-turing-institute/repro-catalogue#69]
Hi, 

I've recently started working a bit on the reproducibility stuff, and Eric suggested I take a look at the README and see whether I can work through it. I'm hoping these comments might provide a useful insight to what it is like using these tools for someone without a super technical background.

**Installation**

- Requires git to be pre-installed. I'm using a windows laptop at the moment so I had to search for this to download.

- An obvious point, but requires the user to start up command line and to enter the commands.
 

**Getting Started**

- For my testing I had to create a new directory and initialise git. 

- I then created created a basic csv file and a python script that outputs some simple data.

**Engage**

- I had some difficulty establishing what `<data directory>` meant. 

- In particular - is this a string that requires speech marks to surround?
- Is it the data itself (e.g. a csv file)?
- An obvious point (not so much for me though!) but the '<' and '>' are ignored.

- I was originally using a directory structure along the lines of .../Turing Work/... - the space in my directory name created some issues, and required me to rename my folders for this to work for me.

- It took me a while (the example usage helped here!) to realise that this was a folder structure containing all the data I was using.

- The code itself was clear.

**Disengage** 

- I found the `\` a bit confusing when I tried to paste them into my command line. Once I removed them, this all worked quite well.

- I think it could be made slightly clearer what the expected process was. My understanding is that one is expected to:
1) engage
2) run analysis script
3) disengage

- I think there's a risk a user might skip the second step. I'm not sure if I myself have made a mistake because I get the following output:

```
results differ in 1 places:
===========================
timestamp
results match in 2 places:
==========================
input_data
code
results could not be compared in 1 places:
==========================================
C:\Users\xukev\Desktop\Turing_Work\test_repo\output_dir\output_data.csv
```

I tried it many times and I got a different time stamp each time. I ran through the process again in order to create two json output files.

**compare**

- Was not clear what `<TIMESTAMP1.json>`. I originally thought that it was simply the name of my Json string, e.g. `20200511-125939.json`. In practice I had to either shift directory to category results, or to add the category results extension. 

- If we're creating the category results directory automatically, would it be easier if we code it so the tool automatically looks inside the category results directory?

- This was my result:

```
results differ in 1 places:
===========================
timestamp
results match in 3 places:
==========================
input_data
code
C:\Users\xukev\Desktop\Turing_Work\test_repo\output_dir\output_data.csv
results could not be compared in 0 places:
==========================================

```
I think this is expected?

**Comment by radka-j** [comment]
This is all really useful, thank you!

**Comment by radka-j** [comment]
Regarding getting different timestamps, that is expected behaviour. 

We were worried that this is not at all clear and that someone might conclude that something has gone wrong based on the output that gets printed (exactly as described above).

Consequently, we made a change to what gets printed (in #68). The current version of the output looks like this:
```
NOTE we expect the timestamp hashes to differ.

results differ in 1 places:
===========================
timestamp

results match in 3 places:
==========================
....
```

@kevinxufs @LouiseABowler do you think this is sufficient or could this be improved?

**Comment by kevinxufs** [comment]
I think that as a user coming into this, it is very intuitive that the two timestamps would differ (as I ran the tool at different times). Just looking at the different json names, I would expect them to be different.

The reason I think that it felt confusing was because in the 'compare' output, it has results differring in 0 places -  so it looked like a mistake had been made as I could not replicate the example. This is especially confusing because the output appears to use two different time stamps variables (TIMESTAMP1.json and TIMESTAMP2.json).

I'm not sure if the example output here was a result of using the same json string twice?

Thanks!

**Comment by radka-j** [comment]
Ah I completely missed that, thanks so much for pointing that out! Yes that example is misleading and wrong.

**Comment by LouiseABowler** [comment]
A couple more to-dos for @radka-j and I - thanks for these comments @kevinxufs! (Copied over from PR #85)
```
Thanks Radka, this looks really good.

Some very small comments.

Prerequisites

I wonder whether it would be better to name these folders something like:
data_dir
code_dir
results_dir

This will make it much more obvious that these are directories (which I struggled with for a while). I think it would also make it clearer that your later example (which is great!) in engage is directly applied onto what has been said here. Currently when I see the example it makes me think that 'data' and 'code' are just placeholder names, whilst you're actually providing an example that would work on our example file structure.

A small point that it isn't super clear to me what a full or relative path means.

disengage

I think an example could be helpful when you say immediately after finishing the analysis. Just so the user can really associate the analysis, with the running of their code.

Something as simple as saying, 'for example, my analysis is done by running my code as an executable file in command prompt. Once I have finished running this code, I then proceed to the disengage stage.'
compare

Another very small point. If you're telling the user to provide the different paths, I think the example should include those paths in them. e.g. compare catalogue_results\200510-120000.json catalogue_results\200510-120000.json

Might not be obvious why you are using cd here.

Thanks!
```
