### ISSUE TITLE
Implement git_query function

### ISSUE THREAD

**Issue by radka-j** [alan-turing-institute/repro-catalogue#9]
This function is called in the [engage.py](https://github.com/alan-turing-institute/repro-catalogue/blob/2745de147f5cb0ba5c8e045e03c868dcbe3d1682/catalogue/engage.py#L5) file.

It should do a git status check described in the README when `catalogue engage` is called. See below comment for more details.

**Comment by Islast** [comment]
The "git_query" line I don't think it was in reference to any particular package, just a function that I meant to write later. The codebase I wrote was *very* incomplete. 

What I had meant `git_query` to do 
* is check the git status of the code directory (hence the args.code argument) 
    * if clean, return true
    * if there are uncommitted changes, ask for the users input
        - offer to stage and commit all and continues (returning True)
        - or to quit (returning False)

**Comment by radka-j** [comment]
@Islast this is really helpful, thank you!

**Comment by edaub** [comment]
This functionality should be easy to implement using the `gitpython` package.
